### 
GET http://localhost:3000/articles

###
POST http://localhost:3000/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MjUzODU4NiwiZXhwIjoxNzQyNTQyMTg2fQ.mPn6iHp6QI-dkrx09TKmyp-DN_ZXBo17khL-2eB_z30
Content-Type: application/json

{
  "title":"API로 생성된 게시글",
  "content":"추가로 생성된 게시글 입니다.",
  "image":""
}

###
GET http://localhost:3000/articles/3967ef44-cfd1-4e71-9066-eb5577feb7ad

### 
DELETE http://localhost:3000/articles/4f724c4b-cfb0-400f-84c8-a4f7ea80f73b

###
PATCH http://localhost:3000/articles/7408b2d5-7cca-4102-8239-d3b6f6009879
Content-Type: application/json

{
  "title":"API로 수정된 게시글",
  "content":"추가로 수정된 게시글 입니다."
}

###
POST http://localhost:3000/articles/1/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MjU0ODg1OCwiZXhwIjoxNzQyNTUyNDU4fQ.ta9KCxBE2GHmJZIja3xo45op0vvhOlgZcYWt_46-HdY
Content-Type: application/json

{
  "content":"댓글입니다."
}

###
POST http://localhost:3000/articles/likes/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0Mjg2NzI4MCwiZXhwIjoxNzQyODcwODgwfQ.Sd3n24oixg6bCmiGa9r87SJ3IfGDZttOFeLBpme0Jxw

###
DELETE http://localhost:3000/articles/likes/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0Mjg2NzI4MCwiZXhwIjoxNzQyODcwODgwfQ.Sd3n24oixg6bCmiGa9r87SJ3IfGDZttOFeLBpme0Jxw