###
GET http://localhost:3000/products

###
POST http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MjUzOTMxNCwiZXhwIjoxNzQyNTQyOTE0fQ.e1r5bJs-6udkLHCg-uj2C_SeMvr25SAzKTSf-W7njaI
Content-Type: application/json

{
  "name":"test",
  "description":"test상품입니다.",
  "price":50000,
  "tags":["전자제품", "노트북"]
}


###
GET http://localhost:3000/products/d8b6677b-5e80-43d5-bb66-4311c461feec

###
DELETE http://localhost:3000/products/20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MjUzOTMxNCwiZXhwIjoxNzQyNTQyOTE0fQ.e1r5bJs-6udkLHCg-uj2C_SeMvr25SAzKTSf-W7njaI


###
PATCH http://localhost:3000/products/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MjUzNzA5MCwiZXhwIjoxNzQzNzQ2NjkwfQ.Hinr3ATQH9qUOG-jb-GcZ_zuC2LOq6U66Mjdgtkbz0E
Content-Type: application/json

{
  "name":"patched",
  "description":"수정된 상품 입니다.",
  "price":30000,
  "tags":["전자제품", "노트북"]
}
