### 회원가입
POST http://localhost:3000/users
Content-Type: application/json

{
  "email":"f@gmail.com",
  "nickname":"8번유저",
  "password":"12341234"
}

### 토큰기반로그인
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email":"0001@gmail.com",
  "password":"56785678"
}

### 토큰재발급
POST http://localhost:3000/users/token/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MjUyNDAwMSwiZXhwIjoxNzQzNzMzNjAxfQ.eCtid0NhflVgYezF2WQEHg-kABFwTdxbzMpUjUi16mw

### 유저정보조회(자신) 
GET http://localhost:3000/users/info
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0Mjc5MDM4NiwiZXhwIjoxNzQzOTk5OTg2fQ.I7O2nMuzC6a7B1lIBKUp2E9VWnT5pmSnk2x5YAvgpMA

### 유저정보수정
PATCH http://localhost:3000/users/patch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0Mjc5MDM4NiwiZXhwIjoxNzQzOTk5OTg2fQ.I7O2nMuzC6a7B1lIBKUp2E9VWnT5pmSnk2x5YAvgpMA
Content-Type: application/json

{
  "nickname":"수정된유저",
  "email":"0001@gmail.com"
}

### 유저비밀번호수정
PATCH http://localhost:3000/users/pwdPatch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0Mjc5MDM4NiwiZXhwIjoxNzQzOTk5OTg2fQ.I7O2nMuzC6a7B1lIBKUp2E9VWnT5pmSnk2x5YAvgpMA
Content-Type: application/json

{
  "password":"12341234",
  "newPassword":"56785678"
}

### 유저상품리스트조회
GET http://localhost:3000/users/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0Mjc5MDM4NiwiZXhwIjoxNzQzOTk5OTg2fQ.I7O2nMuzC6a7B1lIBKUp2E9VWnT5pmSnk2x5YAvgpMA

###
GET http://localhost:3000/users/products/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0Mjg2ODY5MSwiZXhwIjoxNzQyODcyMjkxfQ.5ty34bzQWA-7TV4l0IJmb9une54kiqNGO0Nsg7FpIDE햐