### 회원가입
POST http://localhost:3000/users
Content-Type: application/json

{
  "email":"f@gmail.com",
  "nickname":"8번유저",
  "password":"12341234"
}

### 토큰기반로그인
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email":"twomean99@gmail.com",
  "password":"12341234"
}

### 토큰재발급
POST http://localhost:3000/users/token/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MjUyNDAwMSwiZXhwIjoxNzQzNzMzNjAxfQ.eCtid0NhflVgYezF2WQEHg-kABFwTdxbzMpUjUi16mw

### 유저정보조회(자신) 
GET http://localhost:3000/users/info
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0Mjc3NjU1NSwiZXhwIjoxNzQyNzgwMTU1fQ.upG90ovAysN0GK_vTWG8IQlPowRzEcSVxnjdZcHVFcw

### 유저정보수정
PATCH http://localhost:3000/users/patch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0Mjc3ODU2OCwiZXhwIjoxNzQyNzgyMTY4fQ.V5FRupXbQ6HZrDhFhD6HYFJcS6R6_kpbDjiJeVR0ZNw
Content-Type: application/json

{
  "nickname":"수정된유저",
  "email":"updated@gmail.com"
}