name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/8-sprint-mission # EC2 인스턴스 내 프로젝트 경로로 진입
            git pull origin main # 코드 최신화
            npm install
            npm run build
            npm run prisma:deploy # 예: prisma migrate deploy로 마이그레이션 적용하기
            pm2 reload npm # PM2로 재실행
            echo "Deployment successful!"
